### ISSUE TITLE
$PATH is not set correctly

### ISSUE THREAD

**Issue by sfkleach** [sfkleach/unpacked_poplog_base_v16#4]
At login, I can see that my $PATH has been extended by a Poplog specific path `/usr/local/poplog/V16/poplog_base`. This is an incorrect entry and definitely should not be there. (In addition it hard-codes `V16` which cannot be correct.)
```sh
steve@dev001:~$ echo $PATH | tr : '\012'
/home/linuxbrew/.linuxbrew/bin
/home/linuxbrew/.linuxbrew/sbin
/opt/gatling/bin
/usr/local/maven/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/games
/usr/local/games
/snap/bin
/opt/shakti
/opt/anaconda3/bin
/usr/local/poplog/V16/poplog_base
```

**Comment by throatwobblermangrove3** [comment]
In /etc/environment , the /usr/local/poplog/V16/poplog_base was being set.

$PATH in /etc/environment is updated and this path is removed from /etc/environment

**Comment by throatwobblermangrove3** [comment]
$PATH in /etc/environment is updated and this path is removed from /etc/environment

mtreitel@dev001:~$ echo $PATH | tr : '\012'
/home/linuxbrew/.linuxbrew/bin
/home/linuxbrew/.linuxbrew/sbin
/opt/gatling/bin
/usr/local/maven/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/games
/usr/local/games
/snap/bin
/opt/shakti
